[[constraint]]
  branch = "fix/reset-parent"
  name = "github.com/uphy/go-redmine"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/gocarina/gocsv"
